name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: List files
      run: ls -R

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt

  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download archive text file
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact
          path: artifacts

      - name: List Artifacts
        run: ls -R 

      - name: Cat text file
        run: cat ./artifacts/hello.txt
        
    
